// #include <bits/stdc++.h>
// using namespace std;

// int main ()
// {
//     int t;
//     cin>>t;
//     while(t--)
//     {
//         int n,a,b;
//         cin>>n>>a>>b;
//         string s;
//         cin>>s;
//         int ans =0;
//         int sum = 0;
//         for(int i = 0;i < n;i++)
//         {
//             if(a[i] == '0')
//             {
//                ans = 1;
//                 sum++;
//             }
//             else if(ans == 1)
//             {
//                 if(sum < a)
//                 {}
//                 else
//                 {
//                     aans +=
//                 }
//                 ans = 0;
//                 sum = 0;
//             }

//         }
//     }
// }
